name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9.1', '3.10.18', '3.11.13']

    steps:
    - uses: actions/checkout@v5
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Format check with black
      run: |
        black --check --diff .
        
    - name: Test with pytest
      run: |
        pytest -v --tb=short
        
    - name: Check package build
      run: |
        pip install build twine
        python -m build
        twine check dist/*

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install mypy types-requests
        
    - name: Type check with mypy
      run: |
        mypy bilibili_downloader --ignore-missing-imports || true
        
    - name: Security check with bandit
      run: |
        pip install bandit
        bandit -r bilibili_downloader -ll || true